### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by AryanSharma9917** [AryanSharma9917/Codewise-CLI#4]
### Description

One of the unit test is failing. 
cc : @RakshitKumar04 

### Screenshots

![image](https://github.com/AryanSharma9917/Codewise-CLI/assets/72792907/e18d8396-18a5-4759-b3ae-402abbb29f57)

**Comment by Codecollab-go** [comment]
Hey @AryanSharma9917, any update on this issue or its still the same..?
